---
serviceIp: "127.0.0.1"
servicePort: 8082
amqpPort: 5672
amqpHost: "192.168.56.50"
amqpUsername: "admin"
amqpPassword: "admin"
mongoDbPort: 27017
mongoDbHost: "mongo"
mongoDatabaseName: "claimQuery"
mongoClaimQueryCollectionName: "claims"
