---
serviceIp: "127.0.0.1"
servicePort: 8084
amqpPort: 5672
amqpHost: "192.168.56.50"
claimRegistrationServiceExchangeName: "claim-registration-service"
claimFraudServiceExchangeName: "claim-fraud-service"
