---
serviceIp: "127.0.0.1"
servicePort: 8085
amqpPort: 5672
amqpHost: "127.0.0.1"
claimPaymentServiceExchangeName: "claim-payment-service"
claimCommunicationServiceExchangeName: "claim-communication-service"
claimRegistrationServiceExchangeName: "claim-registration-service"
