---
serviceIp: "0.0.0.0"
servicePort: 8083
amqpPort: 5672
amqpHost: "192.168.56.50"
amqpUsername: "admin"
amqpPassword: "admin"
mongoDbPort: 27017
mongoDbHost: "0.0.0.0"
mongoDatabaseName: "claimRegistration"
mongoClaimCollectionName: "claims"
claimRegistrationServiceExchangeName: "claim-registration-service"
